### ISSUE TITLE
Support the new Face blendshapes graph

### ISSUE THREAD

**Issue by GeorgeS2019** [j20001970/GDMP#12]
This is 2 weeks newer than 0.91 1st Feb 2023 releaes

[Add mediapipe tasks face blendshapes graph](https://github.com/google/mediapipe/commit/ba10ae8410ce431f593c95986a230add675e5ccd)

**Comment by j20001970** [comment]
Hi, what would your usage of face blendshapes graph look like? If I understand it correctly the graph would be applied on top of existing face mesh graph by connecting predicted landmarks to it as input.  If that is the case we will need additional functionality that will add new calculator nodes to initialized graph config on the plugin side.

**Comment by GeorgeS2019** [comment]
@j20001970 
This is the use case: [ARKit 52 blendshapes](https://github.com/google/mediapipe/issues/3421)

This is missing in Godot, the ability to take the webcam and perform face motion capture and drive an avatar e.g. created using industry standards based on 52 blendshapes

This will allow Godot users to be the game engine that supports users e.g. using Android or Web to drive avatars.

Currently, only iPhone with a depth camera can drive the industry standards avatar with 52 blendshapes

**Comment by GeorgeS2019** [comment]
@j20001970  

Thx for updating the mediapipe :-)

**Comment by j20001970** [comment]
> @j20001970
> 
> Thx for updating the mediapipe :-)

No problem :)

**Comment by GeorgeS2019** [comment]
[[Feature Request] face_blendshapes.tflite](https://github.com/keijiro/FaceMeshBarracuda/issues/24)

**Comment by GeorgeS2019** [comment]
@j20001970
@you-win
[See the mediapipe blendshapes in action](https://github.com/google/mediapipe/issues/4162#issuecomment-1467531976)

![msedge_beivNJt8ur](https://user-images.githubusercontent.com/49812372/224948043-6b7f192b-97e8-412e-bfc8-ad6a04a1767e.gif)
