### ISSUE TITLE
Errors in setup.py

### ISSUE THREAD

**Issue by anunknowperson** [j20001970/GDMP#20]
I get these errors when I try to run setup.py. Thank you in advance for your great work.

H:\GDMP>setup.py --godot-binary "C:\Users\Sereja\Desktop\Godot_v4.0.1-stable_win64.exe"
Dumping Extension API
Godot Engine v4.0.1.stable.official.cacf49999 - https://godotengine.org

Traceback (most recent call last):
  File "H:\GDMP\setup.py", line 139, in <module>
    generate_bindings(api_json_path)
  File "H:\GDMP\setup.py", line 31, in generate_bindings
    import binding_generator as bg
ModuleNotFoundError: No module named 'binding_generator'

H:\GDMP>setup.py --extension-api-json "H:\GDMP\extension_api.json"
Traceback (most recent call last):
  File "H:\GDMP\setup.py", line 139, in <module>
    generate_bindings(api_json_path)
  File "H:\GDMP\setup.py", line 31, in generate_bindings
    import binding_generator as bg
ModuleNotFoundError: No module named 'binding_generator'

**Comment by j20001970** [comment]
Please make sure there are `binding_generator.py` in `godot-cpp` submodule.
Maybe you forgot to initialize the submodules:
> git submodule update --init --recursive

**Comment by anunknowperson** [comment]
> Please make sure there are `binding_generator.py` in `godot-cpp` submodule. Maybe you forgot to initialize the submodules:
> 
> > git submodule update --init --recursive

Thanks, I used to download via github because I had some problems with the sub-modules. It's working now.
