### ISSUE TITLE
GDExtension C# bindings made possible by Godot 4.2 Beta 1

### ISSUE THREAD

**Issue by GeorgeS2019** [j20001970/GDMP#25]
Do check out this [new project,](https://github.com/godotengine/godot/pull/82331#issuecomment-1767267091) perhaps the more official way to generate the GDExtension C# Bindings

Tested on c++ GDExtension:
- [Examples/DodgeTheCreeps/DodgeTheCreeps.gdextension](https://github.com/RhubarbVR/GDExtensionCSharp/blob/8bea93a873b5d8b64d0e0ff19544573bc69c3318/Examples/DodgeTheCreeps/DodgeTheCreeps.gdextension)

```dos
dotnet publish DodgeTheCreeps/Source/DodgeTheCreeps.csproj 
-property:GenerateFullPaths=true 
-consoleloggerparameters:NoSummary 
-p:NativeLib=Shared 
--use-current-runtime -o DodgeTheCreeps/Build
```

- [Examples/Summator/Summator.gdextension](https://github.com/RhubarbVR/GDExtensionCSharp/blob/8bea93a873b5d8b64d0e0ff19544573bc69c3318/Examples/Summator/Summator.gdextension)

```dos
dotnet publish Summator/Source/Summator.csproj 
-property:GenerateFullPaths=true 
-consoleloggerparameters:NoSummary 
-p:NativeLib=Shared 
--use-current-runtime -o Summator/Build
```

**Comment by GeorgeS2019** [comment]
@j20001970 
We now have 2024 attempt to generate GDExtension CSharp bindings
https://github.com/godotengine/godot-proposals/issues/8191#issuecomment-1910977324

**Comment by GeorgeS2019** [comment]
@j20001970 

[Godot .NET](https://github.com/godotengine/godot/pull/72883#issuecomment-2041113965) is finally here

**Comment by j20001970** [comment]
Closed in favour of https://github.com/j20001970/GDMP-demo/discussions/6
