### ISSUE TITLE
Camera Helper not working on iOS

### ISSUE THREAD

**Issue by WaterBoiledPizza** [j20001970/GDMP#34]
Following up of this journey of having GDMP on iOS device. Not sure if this is a Godot issue or the library issue, but the mediapipe tasks are not starting.

i've built the `--type release --arch arm64` library and imported it to the GDMP-demo project. Added the messages for privacy permissions (Camera, photo and mic access). The app is able to be installed and opened, and i can navigate to the Hand Landmarker task, but upon clicking the Open camera button, nothing happens.

I went and check the process. I suspect it might be an issue about requesting permission with the camera helper, which did not show up, hence no `_permission_result()` callback and the program cannot proceed.

FYI, I am using iPad Air 5th generation for testing

_Originally posted by @WaterBoiledPizza in https://github.com/j20001970/GDMP/issues/32#issuecomment-1970295648_

**Comment by WaterBoiledPizza** [comment]
Not sure if I am understanding your plugin and how the ios export process for Godot completely, but I found that for ios plugins, there is a specific way of implementing them, instead of putting them in the /addon folder:
https://docs.godotengine.org/en/stable/tutorials/platform/ios/ios_plugin.html#creating-an-ios-plugin

Would this help with the case?

**Comment by j20001970** [comment]
The docs you linked is the plugin system specifically for iOS, while GDMP is a GDNative/GDExtension library compiled from C++ targeting multiple platforms. The library should work as long as you have the library files specified by the path in `GDMP.gdnlib` or `GDMP.gdextension`.

**Comment by j20001970** [comment]
Hi @WaterBoiledPizza, just a reminder that since https://github.com/j20001970/GDMP/commit/4dcf18410ed246638c03dfcccb9b450bcda026ed, requesting camera permission should work again on iOS, I'm unable to test the camera functionality beyond permission part though. Looking forward to see the result if you got time to try out.

**Comment by WaterBoiledPizza** [comment]
> Hi @WaterBoiledPizza, just a reminder that since [4dcf184](https://github.com/j20001970/GDMP/commit/4dcf18410ed246638c03dfcccb9b450bcda026ed), requesting camera permission should work again on iOS, I'm unable to test the camera functionality beyond permission part though. Looking forward to see the result if you got time to try out.

Sorry for the late reply. The library works great on the ios device (iPad air). Thank you!
