### ISSUE TITLE
Unable to run the GDMP Demo Project in godot 4.2.2.stable

### ISSUE THREAD

**Issue by vimalkumar010** [j20001970/GDMP#49]
Hi, 
              I am new to Godot and i am trying to run the GDMP Demo project. I have added the addons folder (v0.4) in the root folder, and enabled the GDMP plugin but i am facing the errors as shown below.

            I am unsure why the MediaPipeFaceDetector and relevants Mediapipe dependencies is not resolving.

![Screenshot from 2024-08-24 15-51-30](https://github.com/user-attachments/assets/69eac0e7-1907-4ba8-a19b-e93ea604312c)

![Screenshot from 2024-08-24 15-53-02](https://github.com/user-attachments/assets/9fc86466-4bda-4c48-840e-3b36ed9c1637)

Operating System: Ubuntu 22.04

Thanks

**Comment by j20001970** [comment]
Hi, can you try running Godot editor in terminal, then open the demo project to see what the error output look like? Most likely it's due to missing library dependencies such as OpenCV.

**Comment by j20001970** [comment]
Well, crashing the official editor isn't what I expected.

Can confirm that GDMP v0.4 that built from ubuntu 22.04 somehow doesn't work on the same release, tested from ubuntu 22.04 docker image running godot in headless mode, though the crash messages are a bit different:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.2.stable.official (15073afe3856abd2aa1622492fe50026c7d63dc1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:158)
Illegal instruction (core dumped)
```

I think there's not much I can help with this problem unfortunately, but as a workaround you can try building the library from source in environment that are isolated from host, there is `flatpak_env.sh` script to help you switch to Freedesktop runtime if flatpak is installed on your machine.

**Comment by j20001970** [comment]
GDMP will use Freedesktop SDK that are independent of specific distro version, as well as building OpenCV from source in the next v0.5 release. While using prebuilt v0.4 libraries on Ubuntu 22.04 crash Godot immediately, building from source with latest commit works as expected (with some Bazel defines for XNNPACK added since the compiler is a bit dated). I think this issue is no longer relevant so I'm closing this, please reopen if there are still problems building from source on Ubuntu 22.04.
