### ISSUE TITLE
Tutorial request

### ISSUE THREAD

**Issue by Anton-31-96** [j20001970/GDMP#8]
Hi! 
Thanks for your work. I am trying to use your project for my game and have faced with some issues. May I ask you to show a tutorial with usage of your project for pose tracking? Thanks a lot! 

Best regards, 
Anton

**Comment by j20001970** [comment]
Hi @Anton-31-96 , thanks for your interest in the project! I was planning to create a demo project for the plugin, I will notify you after the project released.

**Comment by j20001970** [comment]
Hi @Anton-31-96 , the demo project is released, please take a look. https://github.com/j20001970/GDMP-demo
Although the demo is quite barebone for now, it should give a glimpse of how to setup the project for pose tracking.

**Comment by j20001970** [comment]
Hi @Anton-31-96 , is there further need for tutorials or improvement on demo project?

**Comment by j20001970** [comment]
If there is no further need for tutorials I will close the issue then.
Feel free to reopen it if more tutorials requests are needed afterward.
